import contacts from "../data/contact.json"

export const DEFAULT_PROFILE = {
  phone: contacts.freeContact,
  title: "🔱 Tridente Bet 🔱",
  plan: "pro",
  platform_top: [{ name: "Ganamos", url: "" }],  // solo name y url
  platforms_rest: [
    { name: "24Live", url: "" },
    { name: "Agentebet", url: "" },
    { name: "Ajugarvip", url: "" },
    { name: "Apostamos", url: "" },
    { name: "Argentbet", url: "" },
    { name: "Atenas", url: "" },
    { name: "Barbaroja", url: "" },
    { name: "Bet30", url: "" },
    { name: "Bet30Click", url: "" },
    { name: "Bet9k", url: "" },
    { name: "Blackrose", url: "" },
    { name: "Camel", url: "" },
    { name: "Casino33", url: "" },
    { name: "Casino77", url: "" },
    { name: "Casinozeta", url: "" },
    { name: "Celuapuestas", url: "" },
    { name: "Cleopatra", url: "" },
    { name: "Cold", url: "" },
    { name: "Daleplay", url: "" },
    { name: "Doblewin", url: "" },
    { name: "Eljoker", url: "" },
    { name: "Fortubet", url: "" },
    { name: "Galeraverde", url: "" },
    { name: "Ganaencasa", url: "" },
    { name: "Ganamos365", url: "" },
    { name: "Horadeganar", url: "" },
    { name: "Houserocks", url: "" },
    { name: "Jugaygana", url: "" },
    { name: "Konabet", url: "" },
    { name: "Megafaraon", url: "" },
    { name: "Monstergames", url: "" },
    { name: "Multiskin", url: "" },
    { name: "Mustangclub", url: "" },
    { name: "Niloplay", url: "" },
    { name: "Oasis", url: "" },
    { name: "Odin", url: "" },
    { name: "Oropuro", url: "" },
    { name: "Pinkrose", url: "" },
    { name: "Playclub", url: "" },
    { name: "Pulpobet", url: "" },
    { name: "Qsuertudo", url: "" },
    { name: "Reydereyes", url: "" },
    { name: "Thor", url: "" },
    { name: "Tiger", url: "" },
    { name: "Vudu", url: "" },
    { name: "Winss", url: "" },
    { name: "Zeus", url: "" },
    { name: "Zeta", url: "" }
  ]
}

export default DEFAULT_PROFILE
